// Collection of BTS quotes, messages, and inspirational sayings
export const btsQuotes = [
  { korean: '입트면 장난 아니래', english: 'If you bloom, it\'s no joke', source: 'BTS Message to ARMY' },
  { korean: '오늘도 화이팅!', english: 'Fighting today too!', source: 'BTS Daily Motto' },
  { korean: '사랑하고 꿈꾸고 이루어가자', english: 'Love, dream, and achieve', source: 'BTS Philosophy' },
  { korean: '우리는 함께입니다', english: 'We are together', source: 'BTS & ARMY' },
  { korean: '포기하지 말고 앞으로 나아가자', english: 'Don\'t give up, move forward', source: 'BTS Message' },
  { korean: '너 자신을 사랑해', english: 'Love yourself', source: 'Love Yourself Album' },
  { korean: '아미 사랑해', english: 'I love ARMY', source: 'BTS to Fans' },
  { korean: '춤을 춘다는 것은 행복이다', english: 'Dancing is happiness', source: 'J-Hope' },
  { korean: '음악으로 마음을 전하자', english: 'Share our hearts through music', source: 'BTS Mission' },
  { korean: '우리의 노래를 듣고 용기를 얻길 바란다', english: 'I hope you gain courage from our songs', source: 'BTS Letter' },
  { korean: '실패는 성공의 어머니', english: 'Failure is the mother of success', source: 'BTS Philosophy' },
  { korean: '매일 최선을 다하자', english: 'Do your best every day', source: 'BTS Work Ethic' },
  { korean: '혼자가 아니에요', english: 'You\'re not alone', source: 'BTS Message' },
  { korean: '꿈을 꾸고 그 꿈을 추격하라', english: 'Dream and chase that dream', source: 'BTS Philosophy' },
  { korean: '우리는 영원히 함께 할거야', english: 'We\'ll be together forever', source: 'BTS Promise' },
  { korean: '긍정적인 마음으로 살아가자', english: 'Live with a positive heart', source: 'BTS Message' },
  { korean: '자신의 길을 가자', english: 'Walk your own path', source: 'BTS Wisdom' },
  { korean: '마음이 있으면 된다', english: 'Where there\'s a will, there\'s a way', source: 'BTS Belief' },
  { korean: '현재를 즐겨라', english: 'Enjoy the present moment', source: 'BTS Message' },
  { korean: '우리 모두 특별하다', english: 'We are all special', source: 'BTS Inclusivity' },
  { korean: '노래하고 춤을 추자', english: 'Let\'s sing and dance', source: 'BTS Joy' },
  { korean: '진심으로 사랑하자', english: 'Love with sincerity', source: 'BTS Values' },
  { korean: '계속 나아가자', english: 'Keep moving forward', source: 'BTS Determination' },
  { korean: '우리는 할 수 있다', english: 'We can do this', source: 'BTS Empowerment' },
  { korean: '모든 순간이 소중하다', english: 'Every moment is precious', source: 'BTS Mindfulness' },
  { korean: '너에게서 길을 잃지 말고', english: 'Don\'t lose yourself', source: 'Epiphany Lyrics' },
  { korean: '미래가 밝다고 생각해', english: 'I think the future is bright', source: 'BTS Hope' },
  { korean: '함께라면 할 수 있어', english: 'Together we can do it', source: 'BTS Unity' },
  { korean: '용기를 내자', english: 'Let\'s be brave', source: 'BTS Encouragement' },
  { korean: '작은 것부터 시작하자', english: 'Start with the small things', source: 'BTS Philosophy' },
  { korean: '이 순간을 소중히 하자', english: 'Cherish this moment', source: 'BTS Message' },
  { korean: '우리는 빛나고 있어', english: 'We are shining', source: 'BTS Glow' },
  { korean: '노력하면 언젠가 이루어진다', english: 'If you work hard, it will be achieved someday', source: 'BTS Perseverance' },
  { korean: '웃음이 가장 좋은 약이야', english: 'A smile is the best medicine', source: 'BTS Joy' },
  { korean: '우리의 이야기를 들어줘서 고마워', english: 'Thank you for listening to our story', source: 'BTS Gratitude' },
  { korean: '변화를 두려워하지 말자', english: 'Don\'t fear change', source: 'BTS Growth' },
  { korean: '항상 최고의 버전이 되려고 노력해', english: 'Always try to be the best version of yourself', source: 'BTS Self-Improvement' },
  { korean: '음악은 모든 것을 치유한다', english: 'Music heals everything', source: 'BTS Belief' },
  { korean: '우리의 꿈은 영원하다', english: 'Our dreams are eternal', source: 'BTS Vision' },
  { korean: '많은 사람들이 우리를 응원해줘', english: 'Many people support us', source: 'BTS Humility' },
  { korean: '한 발씩 나아가자', english: 'Let\'s take it one step at a time', source: 'BTS Progress' },
  { korean: '진심이 통한다', english: 'Sincerity touches hearts', source: 'BTS Truth' },
  { korean: '우리는 특별한 존재야', english: 'We are special beings', source: 'BTS Identity' },
  { korean: '매 순간을 귀하게 여기자', english: 'Cherish every moment', source: 'BTS Wisdom' },
  { korean: '꿈은 현실이 될 수 있어', english: 'Dreams can become reality', source: 'BTS Inspiration' },
  { korean: '함께 하면 외롭지 않아', english: 'You\'re never lonely when together', source: 'BTS Connection' },
  { korean: '우리가 하는 말을 믿어줘', english: 'Believe what we say', source: 'BTS Trust' },
  { korean: '아픔도 지나간다', english: 'Pain will pass too', source: 'BTS Hope' },
  { korean: '오늘보다 내일이 나을 거야', english: 'Tomorrow will be better than today', source: 'BTS Optimism' },
  { korean: '우리는 함께 성장해', english: 'We grow together', source: 'BTS Evolution' },
  { korean: '자신을 믿어', english: 'Believe in yourself', source: 'BTS Confidence' },
  { korean: '이 길이 맞다고 믿어', english: 'I believe this is the right path', source: 'BTS Faith' },
  { korean: '많은 사람의 마음을 움직이고 싶어', english: 'I want to touch many hearts', source: 'BTS Mission' },
  { korean: '우리는 멈추지 않는다', english: 'We never stop', source: 'BTS Determination' },
  { korean: '흘린 땀은 거짓말을 하지 않는다', english: 'Sweat doesn\'t lie', source: 'BTS Work Ethic' },
  { korean: '주는 것이 받는 것보다 낫다', english: 'It is better to give than to receive', source: 'BTS Values' },
  { korean: '우리는 지칠 줄 모른다', english: 'We never tire', source: 'BTS Energy' },
  { korean: '새로운 날이 또 온다', english: 'A new day comes again', source: 'BTS Hope' },
  { korean: '모두가 주인공이 될 수 있어', english: 'Everyone can be a main character', source: 'BTS Inclusivity' },
  { korean: '우리의 노래는 당신의 친구야', english: 'Our songs are your friend', source: 'BTS Connection' },
];

export function getRandomQuote() {
  return btsQuotes[Math.floor(Math.random() * btsQuotes.length)];
}
